import type { NetworkPreset } from "@/types";

export const PRESETS: NetworkPreset[] = [
	{
		id: "simple-dense",
		name: "Simple Dense",
		description: "A minimal 2-layer network. Good starting point for MNIST.",
		layers: [
			{ type: "flatten" },
			{ type: "dense", units: 128, activation: "relu" },
			{ type: "dense", units: 10, activation: "softmax" },
		],
		recommendedDataset: "mnist",
	},
	{
		id: "deep-dense",
		name: "Deep Dense",
		description: "4-layer network. More capacity for complex patterns.",
		layers: [
			{ type: "flatten" },
			{ type: "dense", units: 256, activation: "relu" },
			{ type: "dense", units: 128, activation: "relu" },
			{ type: "dense", units: 64, activation: "relu" },
			{ type: "dense", units: 10, activation: "softmax" },
		],
		recommendedDataset: "mnist",
	},
	{
		id: "wide-dense",
		name: "Wide Dense",
		description:
			"Wide 3-layer network. Explores width vs depth trade-off. Prone to overfitting.",
		layers: [
			{ type: "flatten" },
			{ type: "dense", units: 512, activation: "relu" },
			{ type: "dense", units: 256, activation: "relu" },
			{ type: "dense", units: 10, activation: "softmax" },
		],
		recommendedDataset: "mnist",
	},
	{
		id: "simple-cnn",
		name: "Simple CNN",
		description: "Conv + Pool + Dense for MNIST",
		inputShape: [28, 28, 1],
		recommendedDataset: "mnist",
		layers: [
			{
				type: "conv2d",
				filters: 32,
				kernelSize: 3,
				strides: 1,
				padding: "same",
				activation: "relu",
			},
			{ type: "maxPooling2d", poolSize: 2, strides: 2 },
			{ type: "flatten" },
			{ type: "dense", units: 64, activation: "relu" },
			{ type: "dense", units: 10, activation: "softmax" },
		],
	},
	{
		id: "lenet-5",
		name: "LeNet-5",
		description: "Classic CNN architecture",
		inputShape: [28, 28, 1],
		recommendedDataset: "mnist",
		layers: [
			{
				type: "conv2d",
				filters: 6,
				kernelSize: 5,
				strides: 1,
				padding: "same",
				activation: "tanh",
			},
			{ type: "maxPooling2d", poolSize: 2, strides: 2 },
			{
				type: "conv2d",
				filters: 16,
				kernelSize: 5,
				strides: 1,
				padding: "valid",
				activation: "tanh",
			},
			{ type: "maxPooling2d", poolSize: 2, strides: 2 },
			{ type: "flatten" },
			{ type: "dense", units: 120, activation: "tanh" },
			{ type: "dense", units: 84, activation: "tanh" },
			{ type: "dense", units: 10, activation: "softmax" },
		],
	},
	{
		id: "deep-cnn",
		name: "Deep CNN",
		description: "Multi-scale feature extraction for CIFAR-10",
		inputShape: [32, 32, 3],
		recommendedDataset: "cifar10",
		layers: [
			{
				type: "conv2d",
				filters: 32,
				kernelSize: 3,
				strides: 1,
				padding: "same",
				activation: "relu",
			},
			{
				type: "conv2d",
				filters: 32,
				kernelSize: 3,
				strides: 1,
				padding: "same",
				activation: "relu",
			},
			{ type: "maxPooling2d", poolSize: 2, strides: 2 },
			{
				type: "conv2d",
				filters: 64,
				kernelSize: 3,
				strides: 1,
				padding: "same",
				activation: "relu",
			},
			{
				type: "conv2d",
				filters: 64,
				kernelSize: 3,
				strides: 1,
				padding: "same",
				activation: "relu",
			},
			{ type: "maxPooling2d", poolSize: 2, strides: 2 },
			{ type: "flatten" },
			{ type: "dense", units: 256, activation: "relu" },
			{ type: "dropout", rate: 0.5 },
			{ type: "dense", units: 10, activation: "softmax" },
		],
	},
];

export const PRESET_MAP: Record<string, NetworkPreset> = Object.fromEntries(
	PRESETS.map((p) => [p.id, p]),
);
